tcp:
  routers:
    ocp-api-router:
      entryPoints:
        - "tcp"
      rule: "HostSNI(`api.YOURCLUSTER-NAME.YOUR-DOMAIN`)"
      # e.g. - api.mycluster.example.com
      service: "ocp-api-service"
      tls:
        passthrough: true
    
    ocp-apps-router:
      service: "ocp-apps-service"
      entryPoints:
        - "https"
      rule: "HostSNI(`console-openshift-console.apps.YOURCLUSTER-NAME.YOUR-DOMAIN`,`oauth-openshift.YOURCLUSTER-NAME.YOUR-DOMAIN`)"
      # e.g. - console-openshift-console.apps.mycluster.example.com
      #      - coauth-openshift.apps.mycluster.example.com
      tls:
        passthrough: true
  
  services:
    ocp-api-service:
      loadBalancer:
        servers:
          - address: "REPLACE_THIS_WITH_YOUR_OCP_API_IP_ADDRESS:6443"
    ocp-apps-service:
      loadBalancer:
        servers:
          - address: "REPLACE_THIS_WITH_YOUR_OCP_INGRESS_IP_ADDRESS:443"

http:
  routers:
    traefik:
      service: api@internal
      entryPoints:
      - https
      rule: "Host(`traefik.YOURCLUSTER-NAME.YOUR-DOMAIN`)"
      # e.g. - traefik.mycluster.example.com
      tls:
        certResolver: dns-cloudflare
        domains:
        - main: traefik.YOURCLUSTER-NAME.YOUR-DOMAIN
        # e.g. - traefik.mycluster.example.com